# Generated by Django 5.2.4 on 2025-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_api', '0002_remove_calllog_created_at_calllog_sid_calllog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20, null=True),
        ),
    ]
